All features to achieve, ready for pre-release

diff --git a/tools/aaciocpp.in b/tools/aaciocpp.in
--- a/tools/aaciocpp.in
+++ b/tools/aaciocpp.in
@@ -5,7 +5,27 @@ if [ "${AACIO_BIN_INSTALL_DIR}" == "." ]; then
   AACIO_BIN_INSTALL_DIR=`pwd`
 fi
 AACIO_INSTALL_DIR=`dirname ${AACIO_BIN_INSTALL_DIR}`
-ABIGEN=${AACIO_INSTALL_DIR}/bin/aacio-abigen
+if [ -x "@CMAKE_BINARY_DIR@/programs/aacio-abigen/aacio-abigen" ]; then
+    ABIGEN="@CMAKE_BINARY_DIR@/programs/aacio-abigen/aacio-abigen"
+elif [ -x "${AACIO_INSTALL_DIR}/bin/aacio-abigen" ]; then
+    ABIGEN=${AACIO_INSTALL_DIR}/bin/aacio-abigen
+fi
+if [ -x "@CMAKE_BINARY_DIR@/externals/binaryen/bin/aacio-s2wasm" ]; then
+    AACIO_S2WASM="@CMAKE_BINARY_DIR@/externals/binaryen/bin/aacio-s2wasm"
+elif [ -x "${AACIO_INSTALL_DIR}/bin/aacio-s2wasm" ]; then
+    AACIO_S2WASM="${AACIO_INSTALL_DIR}/bin/aacio-s2wasm"
+else
+    echo "aacio-s2wasm not found either built or installed"
+    exit 12
+fi
+if [ -x "@CMAKE_BINARY_DIR@/libraries/wasm-jit/Source/Programs/aacio-wast2wasm" ]; then
+    AACIO_WAST2WASM="@CMAKE_BINARY_DIR@/libraries/wasm-jit/Source/Programs/aacio-wast2wasm"
+elif [ -x "${AACIO_INSTALL_DIR}/bin/aacio-wast2wasm" ]; then
+    AACIO_WAST2WASM="${AACIO_INSTALL_DIR}/bin/aacio-wast2wasm"
+else
+    echo "aacio-wast2wasm not found either built or installed"
+    exit 14
+fi
 BOOST_INCLUDE_DIR=@Boost_INCLUDE_DIR@
 function copy_skeleton {
     set -e
@@ -41,8 +61,14 @@ function build_contract {
 
         ($PRINT_CMDS; @WASM_CLANG@ -emit-llvm -O3 --std=c++14 --target=wasm32 -nostdinc \
                                    -DBOOST_DISABLE_ASSERTS -DBOOST_EXCEPTION_DISABLE \
-                                   -nostdlib -nostdlibinc -ffreestanding -nostdlib -fno-threadsafe-statics -fno-rtti \
-                                   -fno-exceptions -I ${AACIO_INSTALL_DIR}/include \
+                                   -nostdlib -nostdlibinc -ffreestanding -nostdlib \
+                                   -fno-threadsafe-statics -fno-rtti -fno-exceptions \
+                                   -I @CMAKE_BINARY_DIR@/contracts \
+                                   -I @CMAKE_SOURCE_DIR@/contracts \
+                                   -I @CMAKE_SOURCE_DIR@/contracts/libc++/upstream/include \
+                                   -I @CMAKE_SOURCE_DIR@/contracts/musl/upstream/include \
+                                   -I @CMAKE_SOURCE_DIR@/externals/magic_get/include \
+                                   -I ${AACIO_INSTALL_DIR}/include \
                                    -I${AACIO_INSTALL_DIR}/include/libc++/upstream/include \
                                    -I${AACIO_INSTALL_DIR}/include/musl/upstream/include \
                                    -I${BOOST_INCLUDE_DIR} \
@@ -53,16 +79,22 @@ function build_contract {
 
     done
 
-    ($PRINT_CMDS; @WASM_LLVM_LINK@ -only-needed -o $workdir/linked.bc $workdir/built/* \
-                                   ${AACIO_INSTALL_DIR}/usr/share/aacio/contractsdk/lib/aaciolib.bc \
-                                   ${AACIO_INSTALL_DIR}/usr/share/aacio/contractsdk/lib/libc++.bc \
-                                   ${AACIO_INSTALL_DIR}/usr/share/aacio/contractsdk/lib/libc.bc
-
-
-    )
+    declare -a possible_libs=("@CMAKE_BINARY_DIR@/contracts/aaciolib/aaciolib.bc"
+                              "@CMAKE_BINARY_DIR@/contracts/libc++/libc++.bc"
+                              "@CMAKE_BINARY_DIR@/contracts/musl/libc.bc"
+                              "${AACIO_INSTALL_DIR}/usr/share/aacio/contractsdk/lib/aaciolib.bc"
+                              "${AACIO_INSTALL_DIR}/usr/share/aacio/contractsdk/lib/libc++.bc"
+                              "${AACIO_INSTALL_DIR}/usr/share/aacio/contractsdk/lib/libc.bc")
+    declare libs=""
+    for lib in "${possible_libs[@]}"; do
+        if [ -f "${lib}" ]; then
+            libs="${libs} ${lib}"
+        fi
+    done
+    ($PRINT_CMDS; @WASM_LLVM_LINK@ -only-needed -o $workdir/linked.bc $workdir/built/* ${libs})
     ($PRINT_CMDS; @WASM_LLC@ -thread-model=single --asm-verbose=false -o $workdir/assembly.s $workdir/linked.bc)
-    ($PRINT_CMDS; ${AACIO_INSTALL_DIR}/bin/aacio-s2wasm -o $outname -s 16384 $workdir/assembly.s)
-    ($PRINT_CMDS; ${AACIO_INSTALL_DIR}/bin/aacio-wast2wasm $outname ${outname%.*}.wasm -n)
+    ($PRINT_CMDS; ${AACIO_S2WASM} -o $outname -s 16384 $workdir/assembly.s)
+    ($PRINT_CMDS; ${AACIO_WAST2WASM} $outname ${outname%.*}.wasm -n)
 
     ($PRINT_CMDS; rm -rf $workdir)
     set +e
@@ -79,6 +111,11 @@ function generate_abi {
     
     ${ABIGEN} -extra-arg=-c -extra-arg=--std=c++14 -extra-arg=--target=wasm32 \
         -extra-arg=-nostdinc -extra-arg=-nostdinc++ -extra-arg=-DABIGEN \
+        -extra-arg=-I@CMAKE_SOURCE_DIR@/contracts \
+        -extra-arg=-I@CMAKE_BINARY_DIR@/contracts \
+        -extra-arg=-I@CMAKE_SOURCE_DIR@/contracts/libc++/upstream/include \
+        -extra-arg=-I@CMAKE_SOURCE_DIR@/contracts/musl/upstream/include \
+        -extra-arg=-I@CMAKE_SOURCE_DIR@/externals/magic_get/include \
         -extra-arg=-I${AACIO_INSTALL_DIR}/include/libc++/upstream/include \
         -extra-arg=-I${AACIO_INSTALL_DIR}/include/musl/upstream/include \
         -extra-arg=-I${BOOST_INCLUDE_DIR} \
